=== drmilde/epxml-website/website.dtd
<!ELEMENT website (content)>

<!ELEMENT content (kopf?, koerper)>
<!ELEMENT kopf (titel, stile, externes)>
<!ELEMENT titel (#PCDATA)>
<!ELEMENT stile (stil*)>
<!ELEMENT externes (extern*)>

<!ELEMENT stil (#PCDATA)>
<!ELEMENT extern (#PCDATA)>

<!ELEMENT koerper (inhalt*)>
<!ELEMENT inhalt (text|bild)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT bild (#PCDATA)>


<!ATTLIST bild
quelle CDATA #REQUIRED>

<!ATTLIST extern
verweis CDATA #REQUIRED>

=== drmilde/epxml-website/website.xml
<?xml version="1.0" ?>
<!DOCTYPE website SYSTEM "website.dtd">
<website>
  <content>
    <kopf>
      <titel>Meine kleine Webseite</titel>
      <stile>
	<stil>Hier koennte ihr Stil stehen.</stil>
      </stile>
      <externes>
	<extern verweis="#verweis">Ich moechte Bootstrap benutzen</extern>
      </externes>
    </kopf>
    <koerper>
      <inhalt>
	<!-- one of (bild text) -->
	<text>Hier steht ein bisschen Text</text>
      </inhalt>
      <inhalt>
	<bild quelle="#quelle">Hier ist ein bild</bild>
      </inhalt>
    </koerper>
  </content>
</website>
